version: '3.8'

services:
  web:
    build: ./social_network
    volumes:
      - ./social_network:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data:
