# Generated by Django 5.1.1 on 2024-09-28 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_friend_request_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="dateJoined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="blocked_user",
        ),
        migrations.CreateModel(
            name="Blocked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blockedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blockedUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="myBlockList",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "SENT"),
                            ("accepted", "ACCEPTED"),
                            ("rejected", "REJECTED"),
                        ],
                        default="sent",
                        max_length=8,
                    ),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "requestSentOn",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "requestBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requestTo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("requestBy", "requestTo")},
            },
        ),
        migrations.DeleteModel(
            name="Friend_Request",
        ),
    ]
