# Generated by Django 5.1.1 on 2024-09-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_date_joined_user_datejoined_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocked',
            unique_together={('blockedBy', 'blockedUser')},
        ),
    ]
