# Generated by Django 5.1.1 on 2024-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend_request",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "SENT"),
                    ("accepted", "ACCEPTED"),
                    ("rejected", "REJECTED"),
                ],
                default="sent",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
