# Generated by Django 5.1.1 on 2024-09-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_friend_request_status_alter_user_password"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friend_request",
            unique_together={("request_by", "request_to")},
        ),
    ]
