version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=social
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DB_HOST=db  # Use 'db' if that's the service name in docker-compose
      - DB_PORT=5432
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=social
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
